export const RESTAURANT_DATA = 'RESTAURANT_DATA';
export const HAS_GEOLOCATION = 'HAS_GEOLOCATION';
export const UPDATE_USER_COORDS = 'UPDATE_USER_COORDS';
export const GET_RESTAURANT_SUCCESS = 'GET_RESTAURANT_SUCCESS';
export const GET_RESTAURANT_FAIL = 'GET_RESTAURANT_FAIL';